#!/bin/sh

bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         30
bspc config right_padding       0
bspc config left_padding        0
bspc config bottom_padding      0

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer-action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true

bspc config normal_border_color '#3f444a'
bspc config active_border_color '#46d9ff'
bspc config focused_border_color '#46d9ff'
