#!/bin/sh

xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1366x768 --rotate normal --right-of eDP-1 &

bspc monitor eDP-1 -d 1 2 3 4 5 6
bspc monitor HDMI-1 -d 7 8 9 0
